// lib/instructors-mock-data.ts
import type { InstructorData } from '@/components/tables/InstructorsTable';
import type { InstructorMetricData } from '@/components/layouts/InstructorMetrics';

// Mock performance metrics for instructors page
export const mockInstructorPerformanceMetrics: InstructorMetricData[] = [
  {
    title: 'Top Earner',
    amount: '$1,580 CAD',
    instructorName: 'Rob Lorence',
  },
  {
    title: 'Most distance covered',
    amount: '$1,580 CAD',
    instructorName: 'John Doe',
  },
  {
    title: 'Most ride accepted',
    amount: '$1,580 CAD',
    instructorName: 'Mira Mir',
  },
];

// Mock instructor data
export const mockInstructors: InstructorData[] = [
  {
    id: '1',
    fullName: 'Rob Lorence',
    email: 'rob.lorence@email.com',
    carDetails: '2022 Honda Civic',
    withdrawnAmount: 1200,
    vaultAmount: 380,
    avgWage: 75,
    avgTime: '2.5hr',
    avgDistance: '45km',
    address: '123 Main St, Toronto, ON',
    rating: 4.8,
  },
  {
    id: '2',
    fullName: 'John Doe',
    email: 'john.doe@email.com',
    carDetails: '2023 Toyota Corolla',
    withdrawnAmount: 980,
    vaultAmount: 600,
    avgWage: 68,
    avgTime: '3.2hr',
    avgDistance: '52km',
    address: '456 Oak Ave, Mississauga, ON',
    rating: 4.6,
  },
  {
    id: '3',
    fullName: 'Mira Mir',
    email: 'mira.mir@email.com',
    carDetails: '2021 Nissan Sentra',
    withdrawnAmount: 1450,
    vaultAmount: 130,
    avgWage: 82,
    avgTime: '2.8hr',
    avgDistance: '38km',
    address: '789 Pine Rd, North York, ON',
    rating: 4.9,
  },
  {
    id: '4',
    fullName: 'Sarah Wilson',
    email: 'sarah.wilson@email.com',
    carDetails: '2022 Hyundai Elantra',
    withdrawnAmount: 756,
    vaultAmount: 824,
    avgWage: 71,
    avgTime: '2.1hr',
    avgDistance: '41km',
    address: '321 Elm St, Etobicoke, ON',
    rating: 4.7,
  },
  {
    id: '5',
    fullName: 'Michael Brown',
    email: 'michael.brown@email.com',
    carDetails: '2023 Mazda3',
    withdrawnAmount: 1089,
    vaultAmount: 491,
    avgWage: 79,
    avgTime: '2.9hr',
    avgDistance: '47km',
    address: '654 Maple Ave, Scarborough, ON',
    rating: 4.5,
  },
  {
    id: '6',
    fullName: 'Emily Davis',
    email: 'emily.davis@email.com',
    carDetails: '2021 Kia Forte',
    withdrawnAmount: 623,
    vaultAmount: 957,
    avgWage: 65,
    avgTime: '3.5hr',
    avgDistance: '55km',
    address: '987 Cedar Dr, Richmond Hill, ON',
    rating: 4.8,
  },
  {
    id: '7',
    fullName: 'Alex Johnson',
    email: 'alex.johnson@email.com',
    carDetails: '2022 Volkswagen Jetta',
    withdrawnAmount: 1334,
    vaultAmount: 246,
    avgWage: 88,
    avgTime: '2.3hr',
    avgDistance: '43km',
    address: '147 Birch St, Markham, ON',
    rating: 4.6,
  },
  {
    id: '8',
    fullName: 'Lisa Anderson',
    email: 'lisa.anderson@email.com',
    carDetails: '2023 Subaru Impreza',
    withdrawnAmount: 892,
    vaultAmount: 688,
    avgWage: 73,
    avgTime: '2.7hr',
    avgDistance: '49km',
    address: '258 Spruce Ave, Vaughan, ON',
    rating: 4.7,
  },
];