// lib/ride-session-mock-data.ts
import type { RideSessionData } from '@/components/tables/RideSessionsTable';
import type { MetricData } from '@/components/layouts/KeyMetrics';
import { DollarSign, Users, Calculator, Route } from 'lucide-react';

// Mock metrics for ride sessions page
export const mockRideSessionMetrics: MetricData[] = [
  {
    title: 'Total Revenue',
    value: '$25k',
    icon: DollarSign,
  },
  {
    title: 'Total instructors',
    value: '07',
    icon: Users,
  },
  {
    title: 'Avg. Salary per session',
    value: '$75',
    icon: Calculator,
  },
  {
    title: 'Avg. Distance',
    value: '120km',
    icon: Route,
  }
];

// Mock ride session data
export const mockRideSessions: RideSessionData[] = [
  {
    id: '1',
    userName: 'Sarah Johnson',
    centerName: 'Downsview',
    pickupLocation: '123 Main St --- 456 Oak Ave',
    dateTime: 'December 15, 2024 - 2:30 PM',
    testType: 'G1',
    price: 200,
    instructorName: 'John Smith',
    distance: '120 km',
    duration: '3hr',
    status: 'completed',
  },
  {
    id: '2',
    userName: 'Mike Chen',
    centerName: 'Etobicoke',
    pickupLocation: 'Meet at Center --- 789 Pine Rd',
    dateTime: 'December 16, 2024 - 10:00 AM',
    testType: 'G2',
    price: 200,
    instructorName: 'Emily Davis',
    distance: '120 km',
    duration: '4hr',
    status: 'on_progress',
  },
  {
    id: '3',
    userName: 'Emily Rodriguez',
    centerName: 'Mississauga',
    pickupLocation: '321 Elm St --- 654 Maple Ave',
    dateTime: 'December 17, 2024 - 1:15 PM',
    testType: 'G2',
    price: 200,
    instructorName: 'Michael Brown',
    distance: '120 km',
    duration: '2hr 30m',
    status: 'completed',
  },
  {
    id: '4',
    userName: 'David Kim',
    centerName: 'North York',
    pickupLocation: '777 Cedar Dr --- 888 Birch St',
    dateTime: 'December 18, 2024 - 3:45 PM',
    testType: 'G2',
    price: 200,
    instructorName: 'Sarah Wilson',
    distance: '120 km',
    duration: '2hr 50m',
    status: 'completed',
  },
  {
    id: '5',
    userName: 'Jessica Brown',
    centerName: 'Scarborough',
    pickupLocation: '999 Spruce Ave --- 111 Willow Rd',
    dateTime: 'December 19, 2024 - 11:30 AM',
    testType: 'G1',
    price: 200,
    instructorName: 'Alex Johnson',
    distance: '120 km',
    duration: '3hr',
    status: 'scheduled',
  },
  {
    id: '6',
    userName: 'Robert Taylor',
    centerName: 'Markham',
    pickupLocation: '222 Poplar St --- 333 Cherry Lane',
    dateTime: 'December 20, 2024 - 9:00 AM',
    testType: 'G2',
    price: 200,
    instructorName: 'Lisa Anderson',
    distance: '120 km',
    duration: '4hr',
    status: 'completed',
  },
  {
    id: '7',
    userName: 'Amanda White',
    centerName: 'Richmond Hill',
    pickupLocation: '444 Pine Ridge --- 555 Oak Valley',
    dateTime: 'December 21, 2024 - 4:00 PM',
    testType: 'G1',
    price: 200,
    instructorName: 'David Martinez',
    distance: '120 km',
    duration: '2hr 20m',
    status: 'cancelled',
  },
  {
    id: '8',
    userName: 'Kevin Lee',
    centerName: 'Vaughan',
    pickupLocation: '666 Aspen Dr --- 777 Hickory Ave',
    dateTime: 'December 22, 2024 - 12:00 PM',
    testType: 'G2',
    price: 200,
    instructorName: 'Jennifer Garcia',
    distance: '120 km',
    duration: '3hr 10m',
    status: 'scheduled',
  },
];